### ISSUE TITLE
Configuration using `with: ...` in workflow yaml?

### ISSUE THREAD

**Issue by anp** [actions-rs/grcov#113]
## Motivation

It would be nice to configure grcov inline with my other workflow commands, similar to how the other actions-rs actions work.

## Workflow example

```yaml
- uses: actions-rs/grcov@v0.1
  with:
    branch: true
    ignore-not-existing: true
    llvm: true
    filter: covered
    output-type: lcov
    output-path: ./lcov.info
    prefix-dir: /home/user/build/
    ignore:
      - "/*"
      - "C:/*"
      - "../*"
    path-mapping:
      - "/path1"
      - "/path2"
```

## Additional context

I think this method of configuration should probably be mutually exclusive with the separate configuration file.
