### ISSUE TITLE
Generater report failed

### ISSUE THREAD

**Issue by tu6ge** [actions-rs/grcov#142]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about bugs reporting: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#reporting-bugs
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Description

In today, I am runing my github action with `actions-rs/grcov@v0.1`,  then run `coverallsapp/github-action` , it is return Error :

```
Error: ENOENT: no such file or directory, open '/tmp/grcov-report-n2jbbrhhsc'
```

first time, I thought it was their ( `coverallsapp/github-action`) problem. then I tried to change it settings multiple times :

- one 
```
- name: Coveralls upload
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
```
- two
```
 - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
```
- three
```
 - name: Coveralls upload
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.coverage.outputs.report }}
```
- four
```
 - name: Coveralls upload
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

They all failed

## Workflow code

Listed up
 
## Action output
 
This is some time github action log : https://github.com/tu6ge/oss-rs/actions

## Expected behavior

success output report

## Additional context

no more info
