### ISSUE TITLE
crate with same name as repository ignored

### ISSUE THREAD

**Issue by vitorenesduarte** [actions-rs/grcov#73]
## Description

I have a repository with a workspace containing 4 crates.
- Repository named fantoch: https://github.com/vitorenesduarte/fantoch
- Crates:
  1. fantoch
  2. fantoch_ps
  3. fantoch_timing
  4. fantoch_bote

## Expected behavior

The 4 crates should appear in the coverage report but 1 is ignored. The crate that is ignored is the first one, fantoch, which has the same name as the repository.

To make sure that's not a coincidence, I've created a repository named [test](https://github.com/vitorenesduarte/test/) with the same content as fantoch and now all the 4 crates appear in the coverage report.

- coveralls for fantoch: https://coveralls.io/github/vitorenesduarte/fantoch
- coveralls for test: https://coveralls.io/github/vitorenesduarte/test

## [grcov.yml](https://github.com/vitorenesduarte/fantoch/blob/master/.github/grcov.yml)

```yaml
ignore-not-existing: true
output-type: lcov
output-path: ./lcov.info
ignore:
  - "/*"
  - "fantoch_ps/src/bin/*"
  - "fantoch_bote/src/main.rs"
```

## Further considerations

I have also tried `0.2-proto` in this [branch](https://github.com/vitorenesduarte/fantoch/tree/grcov0.2) (it was suggested in #51 for a different issue), but the problem still occurs.

While typing I started wondering if the issue is in `coverallsapp/github-action@master` and not in this action.
