### ISSUE TITLE
Request for adding exclusion settings to the config file.

### ISSUE THREAD

**Issue by unageek** [actions-rs/grcov#80]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

I want the `--excl-*` options added in grcov v0.5.14 (https://github.com/mozilla/grcov/pull/416) to be mapped to grcov.yml  so that one can exclude `#[derive(...)]`, `mod tests { ... }`, etc. from coverage analysis.

grcov.yml

```yaml
excl-line: "#\\[derive\\("
excl-br-line: "#\\[derive\\("
excl-start: "mod tests \\{"
excl-br-start: "mod tests \\{"
```
